notifications:
  email:
    on_success: never
    on_failure: change

os:
  - osx

language: node_js
node_js:
  - "8"

cache:
  timeout: 600
  directories:
    - node_modules

install:
  - npm prune
  - npm install

script:
  - npm test
