module.exports.parseFile = require('./lib/parse')
module.exports.importFolder = require('./lib/import')
module.exports.parseAll = require('./lib/parseAll')
module.exports.importAllr = require('./lib/importAll')
module.exports.find = require('./lib/find')
module.exports.createNewFile = require('./lib/createNew')
